# Type stubs for mypy to ignore CFFI-related issues
from typing import Any

class CData:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

def string(value: Any) -> bytes: ...
def new(ctype: str, *args: Any) -> Any: ...
def buffer(cdata: Any, size: int) -> bytes: ...
def dlopen(name: str) -> CData: ...

NULL: Any
